import javax.swing.JTextField;

public class FindDiamondGUI extends javax.swing.JFrame {

	public FindDiamondGUI() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jTextField2 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jTextField2.setText("Find: Enter Item Code");
		jTextField2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField2ActionPerformed(evt);
			}
		});

		jButton1.setText("Find");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jTextArea1.setEditable(false);
		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(161, 161, 161).addComponent(jButton1))
								.addGroup(layout.createSequentialGroup().addGap(128, 128, 128).addComponent(jTextField2,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(0, 122, Short.MAX_VALUE))
						.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jScrollPane1)))
				.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(38, Short.MAX_VALUE)
						.addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18).addComponent(jButton1).addGap(18, 18, 18)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(63, 63, 63)));

		pack();
	}// </editor-fold>

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		jTextArea1.setText("");
		JTextField[] textFields = { jTextField2 };
		boolean flag = Inventory.checkInputs(textFields);
		if (flag == false) { // checks if all fields entered
			jTextArea1.append("Please enter all fields.");
			return;
		}
		Round round = Round.find(Integer.parseInt(jTextField2.getText()));
		Taper taper = Taper.find(Integer.parseInt(jTextField2.getText()));
		Baguette baguette = Baguette.find(Integer.parseInt(jTextField2.getText()));

		if (round != null) {
			double averageP = Inventory.round(round.getPrice() / round.getWeight());
			jTextArea1.append("Price/Carat = " + averageP + "\n");
			// gives a statistic on the price/carat
			jTextArea1.append(round.toString()); // printed once found using toString()
			return; // exits early for efficiency
		} else if (taper != null) {
			double averageP = taper.getPrice() / taper.getPieces();
			double averageW = taper.getWeight() / taper.getPieces();
			jTextArea1.append("Price/Piece = " + Inventory.round(averageP) + " (per " + Inventory.round(averageW)
					+ " carats)" + "\n"); // gives a statistic on the price/piece
			jTextArea1.append(taper.toString());
			return;
		} else if (baguette != null) {
			double averageP = baguette.getPrice() / baguette.getPieces();
			double averageW = baguette.getWeight() / baguette.getPieces();
			jTextArea1.append("Price/Piece = " + Inventory.round(averageP) + " (per " + Inventory.round(averageW)
					+ " carats)" + "\n"); 
			jTextArea1.append(baguette.toString());
		} else {
			jTextArea1.append("Stock with Item Code " + jTextField2.getText() + " does not exist"); //if not found
		} 
	}

	private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(FindDiamondGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(FindDiamondGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(FindDiamondGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(FindDiamondGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new FindDiamondGUI().setVisible(true);
			}
		});
	}

	// Variables declaration 
	private javax.swing.JButton jButton1; // find button
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1; // for output
	private javax.swing.JTextField jTextField2; // for input
}
