public class ViewStocksGUI extends javax.swing.JFrame {

	/**
	 * Creates new form ViewStocks
	 */
	public ViewStocksGUI() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jButton1 = new javax.swing.JButton();
		jComboBox1 = new javax.swing.JComboBox<>();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jComboBox2 = new javax.swing.JComboBox<>();
		jLabel3 = new javax.swing.JLabel();
		jComboBox3 = new javax.swing.JComboBox<>();
		jButton2 = new javax.swing.JButton();
		jTextField1 = new javax.swing.JTextField();
		jComboBox4 = new javax.swing.JComboBox<>();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jTextArea1.setEditable(false);
		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		jButton1.setText("View");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "Price", "Weight", "Cut", "Clarity", "Colour", "ItemCode" }));
		jComboBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox1ActionPerformed(evt);
			}
		});

		jLabel1.setText("Sort:");

		jLabel2.setText("Average $/Carat:");

		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "Excellent", "Very Good", "Good", "Fair", "Poor"}));
		jComboBox2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox2ActionPerformed(evt);
			}
		});

		jLabel3.setText("View Type:");

		jComboBox3
				.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Round", "Taper", "Baguette", "All" }));
		jComboBox3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox3ActionPerformed(evt);
			}
		});

		jButton2.setText("Calculate");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jTextField1.setEditable(false);

		jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cut", "Clarity", "Colour" }));
		jComboBox4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox4ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jScrollPane1).addContainerGap())
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addGroup(layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(50, 50, 50).addComponent(jLabel3)
								.addGap(18, 18, 18)
								.addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel1).addGap(18, 18, 18))
						.addGroup(layout.createSequentialGroup().addGap(15, 15, 15).addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addComponent(jButton2).addGap(18, 18, 18)
										.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 124,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGroup(
										layout.createSequentialGroup().addComponent(jLabel2)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 75,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, Short.MAX_VALUE)
												.addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(37, 37, 37)))))
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jButton1).addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(44, 44, 44)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel1).addComponent(jLabel3)
								.addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(18, 18, 18)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton2).addComponent(jTextField1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGroup(layout.createSequentialGroup().addGap(40, 40, 40).addComponent(jButton1)))
						.addContainerGap(27, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) { // view jButton
		jTextArea1.setText("");
		if (jComboBox3.getSelectedItem().toString().equals("Round")) { // comboBox object --> String
			Round.printRound(jTextArea1); // only prints rounds
		} else if (jComboBox3.getSelectedItem().toString().equals("Taper")) {
			Taper.printTaper(jTextArea1); // only prints tapers
		} else if (jComboBox3.getSelectedItem().toString().equals("Baguette")) {
			Baguette.printBaguette(jTextArea1); // only prints baguettes
		} else if (jComboBox3.getSelectedItem().toString().equals("All")) {
			Inventory.displayAll(jTextArea1); // prints all 
		}
	}

	private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) { // sort comboBox
		if (jComboBox3.getSelectedItem().toString().equals("Round")) {
			Round.sort(jComboBox1.getSelectedItem().toString());
		} else if (jComboBox3.getSelectedItem().toString().equals("Taper")) {
			Taper.sort(jComboBox1.getSelectedItem().toString());
		} else if (jComboBox3.getSelectedItem().toString().equals("Baguette")) { // depending on class
			Baguette.sort(jComboBox1.getSelectedItem().toString());
		}
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) { // calculate button 
		jTextField1.setText(""); 
		String selectedItem = jComboBox3.getSelectedItem().toString();
		String selectedObject = jComboBox2.getSelectedItem().toString();

		switch (selectedItem) {
		case "Round":
			if (jComboBox4.getSelectedItem().toString().equals("Colour")) { // gets 1st character
				Round.average(selectedObject.charAt(0), jTextField1);
			} else { //overloading polymorphism: String vs Char (for colour)
				Round.average(selectedObject, jTextField1); // calls different average method
			}
			break;
		case "Taper":
			if (jComboBox4.getSelectedItem().toString().equals("Colour")) {
				Taper.average(selectedObject.toString().charAt(0), jTextField1);
			} else {
				Taper.average(selectedObject.toString(), jTextField1);
			}
			break;
		case "Baguette":
			if (jComboBox4.getSelectedItem().toString().equals("Colour")) {
				Baguette.average(selectedObject.charAt(0), jTextField1);
			} else {
				Baguette.average(selectedObject, jTextField1);
			}
			break;
		default:
			break;
		}
	}

	private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) { // to print all stock
		if (jComboBox3.getSelectedItem().toString().equals("All")) { // hides all other buttons
			jLabel1.setVisible(false);
			jLabel2.setVisible(false);
			jComboBox1.setVisible(false);
			jComboBox2.setVisible(false);
			jButton2.setVisible(false);
			jTextField1.setVisible(false);
			jComboBox4.setVisible(false);
		} else {
			jLabel1.setVisible(true);
			jLabel2.setVisible(true);
			jComboBox1.setVisible(true);
			jComboBox2.setVisible(true);
			jButton2.setVisible(true);
			jTextField1.setVisible(true);
			jComboBox4.setVisible(false);

		}
	}

	private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) { // type comboBox
		String selectedCategory = jComboBox4.getSelectedItem().toString();
		if (selectedCategory.equals("Colour")) {
			String[] colourOptions = { "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S",
					"T", "U", "V", "W", "X", "Y", "Z" }; // changes the calculation options available based on characteristic
			jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(colourOptions));
		} else if (selectedCategory.equals("Clarity")) {
			String[] clarityOptions = { "FL", "IF", "VVS1", "VVS2", "VS1", "VS2", "SI1", "SI2", "I1", "I2", "I3" };
			jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(clarityOptions));
		} else if (selectedCategory.equals("Cut")) {
			String[] cutOptions = { "Excellent", "Very Good", "Good", "Fair", "Poor" };
			jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(cutOptions));
		}
	}
	
	private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ViewStocksGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ViewStocksGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ViewStocksGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ViewStocksGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ViewStocksGUI().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JComboBox<String> jComboBox1;
	private javax.swing.JComboBox<String> jComboBox2;
	private javax.swing.JComboBox<String> jComboBox3;
	private javax.swing.JComboBox<String> jComboBox4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration
}
